import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  ImageIcon,
  Laptop,
  Loader2,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  User,
  X,
  GraduationCap,
  BookOpen,
  Star,
  Gift,
  Trophy,
  Mail,
  BarChart3,
  Users,
  Copy,
  Upload,
  RefreshCw,
  CheckCircle,
} from "lucide-react"

export type Icon = keyof typeof Icons // アイコン名を型としてエクスポート

export const Icons = {
  logo: Command, // アプリのロゴとしてCommandアイコンを使用（適宜変更可能）
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: ImageIcon,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  check: Check,
  graduationCap: GraduationCap,
  bookOpen: BookOpen,
  star: Star,
  gift: Gift,
  trophy: Trophy,
  mail: Mail,
  barChart3: BarChart3,
  users: Users,
  copy: Copy,
  upload: Upload,
  refreshCw: RefreshCw,
  checkCircle: CheckCircle,
  alertCircle: AlertTriangle,
}
